FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-serving.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements-serving.txt

COPY . .

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "src/serving/dashboard.py", "--server.address=0.0.0.0", "--server.port=8501"]