"""
Project-Derived Knowledge Base Builder
======================================

Stage 4A — Knowledge Base Construction (Stage 1 only)

This module creates Markdown knowledge documents exclusively from
artifacts generated by the project's Data and ML layers.

No external industry claims, benchmarks, assumptions, or fabricated
business rules are introduced here.

Source artifacts include:
    - overall model comparison
    - overall ensemble predictions
    - secondary category/region model summaries
    - secondary forecasts
    - SHAP summaries
    - SHAP top forecast drivers
    - monitoring reports
    - data-quality report

The generated Markdown files are intended to become source documents
for the later RAG/vector-store layer.

Generated structure
-------------------
data/knowledge_base/
├── business_context/
│   ├── overall_forecast_analysis.md
│   ├── category_forecast_analysis.md
│   ├── regional_forecast_analysis.md
│   ├── explainability_context.md
│   ├── monitoring_context.md
│   └── data_quality_context.md
│
└── forecast_history/
    └── historical_forecast_outcomes.md
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd


# ============================================================================
# PROJECT PATHS
# ============================================================================

PROJECT_ROOT = (
    Path(__file__).resolve().parents[2]
)

REPORTS_DIR = (
    PROJECT_ROOT
    / "reports"
)

KNOWLEDGE_BASE_DIR = (
    PROJECT_ROOT
    / "data"
    / "knowledge_base"
)

BUSINESS_CONTEXT_DIR = (
    KNOWLEDGE_BASE_DIR
    / "business_context"
)

FORECAST_HISTORY_DIR = (
    KNOWLEDGE_BASE_DIR
    / "forecast_history"
)


# ============================================================================
# SOURCE FILES
# ============================================================================

SOURCE_FILES = {
    "overall_model_comparison":
        REPORTS_DIR
        / "stage1_overall_model_comparison.csv",

    "overall_ensemble_predictions":
        REPORTS_DIR
        / "stage1_weighted_ensemble_predictions.csv",

    "secondary_model_summary":
        REPORTS_DIR
        / "secondary"
        / "secondary_model_summary.csv",

    "secondary_latest_forecasts":
        REPORTS_DIR
        / "secondary"
        / "secondary_latest_forecasts.csv",

    "secondary_predictions":
        REPORTS_DIR
        / "secondary"
        / "secondary_predictions.parquet",

    "shap_summary":
        REPORTS_DIR
        / "shap"
        / "shap_summary.csv",

    "top_forecast_drivers":
        REPORTS_DIR
        / "shap"
        / "top_forecast_drivers.csv",

    "monitoring_summary":
        REPORTS_DIR
        / "monitoring"
        / "monitoring_summary.json",

    "model_performance":
        REPORTS_DIR
        / "monitoring"
        / "model_performance_report.csv",

    "data_drift":
        REPORTS_DIR
        / "monitoring"
        / "data_drift_report.csv",

    "data_quality":
        REPORTS_DIR
        / "data_quality"
        / "data_quality_report.csv",
}


# ============================================================================
# HELPERS
# ============================================================================

def ensure_directories() -> None:
    """Create the knowledge-base output directories."""

    BUSINESS_CONTEXT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    FORECAST_HISTORY_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


def source_exists(
    source_key: str,
) -> bool:
    """Return whether a configured source artifact exists."""

    path = SOURCE_FILES[source_key]

    return path.is_file()


def load_csv(
    source_key: str,
) -> pd.DataFrame:
    """
    Load a CSV source.

    Missing files are handled explicitly so the generated document
    can report missing upstream artifacts instead of inventing data.
    """

    path = SOURCE_FILES[source_key]

    if not path.is_file():
        raise FileNotFoundError(
            f"Required source file not found:\n{path}"
        )

    return pd.read_csv(
        path
    )


def load_parquet(
    source_key: str,
) -> pd.DataFrame:
    """Load a Parquet source."""

    path = SOURCE_FILES[source_key]

    if not path.is_file():
        raise FileNotFoundError(
            f"Required source file not found:\n{path}"
        )

    return pd.read_parquet(
        path
    )


def load_json(
    source_key: str,
) -> dict[str, Any]:
    """Load a JSON source."""

    path = SOURCE_FILES[source_key]

    if not path.is_file():
        raise FileNotFoundError(
            f"Required source file not found:\n{path}"
        )

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def write_markdown(
    path: Path,
    content: str,
) -> None:
    """Write one Markdown knowledge document."""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        content,
        encoding="utf-8",
    )


def format_number(
    value: Any,
    decimals: int = 2,
) -> str:
    """Format numeric values safely for Markdown."""

    if pd.isna(value):
        return "N/A"

    try:
        return f"{float(value):,.{decimals}f}"

    except (
        TypeError,
        ValueError,
    ):
        return str(value)


def format_date(
    value: Any,
) -> str:
    """Format a date-like value safely."""

    if pd.isna(value):
        return "N/A"

    try:
        return pd.Timestamp(
            value
        ).strftime(
            "%Y-%m-%d"
        )

    except (
        TypeError,
        ValueError,
    ):
        return str(value)


def dataframe_to_markdown(
    df: pd.DataFrame,
    columns: list[str] | None = None,
    max_rows: int | None = None,
) -> str:
    """
    Convert a dataframe to Markdown without depending on optional
    display formatting.
    """

    data = df.copy()

    if columns is not None:
        existing = [
            column
            for column in columns
            if column in data.columns
        ]

        data = data[
            existing
        ]

    if max_rows is not None:
        data = data.head(
            max_rows
        )

    if data.empty:
        return (
            "_No records available._"
        )

    return data.to_markdown(
        index=False
    )


def source_note(
    source_keys: list[str],
) -> str:
    """Create a transparent source section."""

    lines = [
        "## Source artifacts",
        "",
    ]

    for key in source_keys:

        path = SOURCE_FILES[key]

        lines.append(
            f"- `{path.relative_to(PROJECT_ROOT)}`"
        )

    return "\n".join(
        lines
    )


# ============================================================================
# 1. OVERALL FORECAST ANALYSIS
# ============================================================================

def build_overall_forecast_analysis() -> None:
    """Generate overall model/forecast business context."""

    comparison = load_csv(
        "overall_model_comparison"
    )

    ensemble = load_csv(
        "overall_ensemble_predictions"
    )

    lines: list[str] = [
        "# Overall Forecast Analysis",
        "",
        "This document contains project-derived information about "
        "the overall weekly revenue forecasting system.",
        "",
        "It does not contain external industry benchmarks or "
        "unstated business assumptions.",
        "",
        "## Production model decision",
        "",
        "XGBoost is the selected production model for the overall "
        "forecast because it provides consistent TreeSHAP "
        "explanations across all production forecasting levels. "
        "LSTM remains a benchmark in the model comparison.",
        "",
    ]

    if not comparison.empty:

        comparison_view = comparison.copy()

        lines.extend(
            [
                "## Model comparison",
                "",
                dataframe_to_markdown(
                    comparison_view
                ),
                "",
            ]
        )

        best_row = (
            comparison_view.iloc[0]
        )

        lines.extend(
            [
                "### Current ranking",
                "",
                (
                    f"The model ranked first in the stored comparison "
                    f"is **{best_row['model']}**, with mean MAPE "
                    f"of **{format_number(best_row['mean_mape'], 2)}%**."
                ),
                "",
                "The production-model choice is documented separately "
                "from the benchmark ranking so that the agent does not "
                "misrepresent the model-selection decision.",
                "",
            ]
        )

    if not ensemble.empty:

        ensemble["timestamp"] = pd.to_datetime(
            ensemble["timestamp"],
            errors="coerce",
        )

        lines.extend(
            [
                "## Historical ensemble forecast stream",
                "",
                (
                    f"The stored walk-forward ensemble contains "
                    f"**{len(ensemble):,} forecast observations**."
                ),
                "",
                (
                    f"Validation period covered: "
                    f"**{format_date(ensemble['timestamp'].min())}** "
                    f"to "
                    f"**{format_date(ensemble['timestamp'].max())}**."
                ),
                "",
            ]
        )

    lines.extend(
        [
            source_note(
                [
                    "overall_model_comparison",
                    "overall_ensemble_predictions",
                ]
            ),
            "",
        ]
    )

    write_markdown(
        BUSINESS_CONTEXT_DIR
        / "overall_forecast_analysis.md",
        "\n".join(lines),
    )


# ============================================================================
# 2. CATEGORY FORECAST ANALYSIS
# ============================================================================

def build_category_forecast_analysis() -> None:
    """Generate project-derived category forecast context."""

    summary = load_csv(
        "secondary_model_summary"
    )

    forecasts = load_csv(
        "secondary_latest_forecasts"
    )

    summary = summary[
        summary[
            "series_type"
        ].astype(str).str.lower()
        == "category"
    ].copy()

    forecasts = forecasts[
        forecasts[
            "series_type"
        ].astype(str).str.lower()
        == "category"
    ].copy()

    lines: list[str] = [
        "# Category Forecast Analysis",
        "",
        "This document contains project-derived forecast information "
        "for the 15 approved business categories.",
        "",
        "All category forecasting is performed using XGBoost with "
        "the approved walk-forward validation design.",
        "",
        "## Category model performance",
        "",
        dataframe_to_markdown(
            summary,
            columns=[
                "series_id",
                "mean_mape",
                "mean_rmse",
                "mean_mae",
                "mean_interval_coverage_pct",
                "rank_within_type",
            ],
        ),
        "",
    ]

    if not forecasts.empty:

        forecasts["timestamp"] = pd.to_datetime(
            forecasts["timestamp"],
            errors="coerce",
        )

        lines.extend(
            [
                "## Latest category forecasts",
                "",
                dataframe_to_markdown(
                    forecasts.sort_values(
                        [
                            "series_id",
                            "timestamp",
                        ]
                    ),
                    columns=[
                        "series_id",
                        "timestamp",
                        "forecast_revenue",
                        "lower_80",
                        "upper_80",
                    ],
                ),
                "",
            ]
        )

    lines.extend(
        [
            "## Interpretation boundary",
            "",
            "The forecast values in this document come directly "
            "from the project's saved ML outputs. No external "
            "market benchmark is assumed.",
            "",
            source_note(
                [
                    "secondary_model_summary",
                    "secondary_latest_forecasts",
                ]
            ),
            "",
        ]
    )

    write_markdown(
        BUSINESS_CONTEXT_DIR
        / "category_forecast_analysis.md",
        "\n".join(lines),
    )


# ============================================================================
# 3. REGIONAL FORECAST ANALYSIS
# ============================================================================

def build_regional_forecast_analysis() -> None:
    """Generate project-derived regional forecast context."""

    summary = load_csv(
        "secondary_model_summary"
    )

    forecasts = load_csv(
        "secondary_latest_forecasts"
    )

    summary = summary[
        summary[
            "series_type"
        ].astype(str).str.lower()
        == "region"
    ].copy()

    forecasts = forecasts[
        forecasts[
            "series_type"
        ].astype(str).str.lower()
        == "region"
    ].copy()

    lines: list[str] = [
        "# Regional Forecast Analysis",
        "",
        "This document contains project-derived forecast information "
        "for the 5 approved regional series.",
        "",
        "All regional forecasting is performed using XGBoost with "
        "the approved walk-forward validation design.",
        "",
        "## Regional model performance",
        "",
        dataframe_to_markdown(
            summary,
            columns=[
                "series_id",
                "mean_mape",
                "mean_rmse",
                "mean_mae",
                "mean_interval_coverage_pct",
                "rank_within_type",
            ],
        ),
        "",
    ]

    if not forecasts.empty:

        forecasts["timestamp"] = pd.to_datetime(
            forecasts["timestamp"],
            errors="coerce",
        )

        lines.extend(
            [
                "## Latest regional forecasts",
                "",
                dataframe_to_markdown(
                    forecasts.sort_values(
                        [
                            "series_id",
                            "timestamp",
                        ]
                    ),
                    columns=[
                        "series_id",
                        "timestamp",
                        "forecast_revenue",
                        "lower_80",
                        "upper_80",
                    ],
                ),
                "",
            ]
        )

    lines.extend(
        [
            "## Interpretation boundary",
            "",
            "The values in this document are generated exclusively "
            "from the project's forecasting outputs. No external "
            "regional assumptions are added.",
            "",
            source_note(
                [
                    "secondary_model_summary",
                    "secondary_latest_forecasts",
                ]
            ),
            "",
        ]
    )

    write_markdown(
        BUSINESS_CONTEXT_DIR
        / "regional_forecast_analysis.md",
        "\n".join(lines),
    )


# ============================================================================
# 4. SHAP / EXPLAINABILITY CONTEXT
# ============================================================================

def build_explainability_context() -> None:
    """Generate business-context documents from TreeSHAP outputs."""

    shap_summary = load_csv(
        "shap_summary"
    )

    drivers = load_csv(
        "top_forecast_drivers"
    )

    lines: list[str] = [
        "# Explainability Context",
        "",
        "This document contains project-derived TreeSHAP "
        "explanations for the production XGBoost models.",
        "",
        "A positive SHAP contribution pushes a forecast upward; "
        "a negative SHAP contribution pushes it downward.",
        "",
        "The explanations are generated from the trained production "
        "XGBoost models and are intended to support later agent "
        "reasoning.",
        "",
        "## Global feature importance summary",
        "",
        dataframe_to_markdown(
            shap_summary,
            columns=[
                "series_type",
                "series_id",
                "top_global_feature",
                "top_global_mean_abs_shap",
                "top_global_importance_pct",
            ],
        ),
        "",
        "## Top local forecast drivers",
        "",
        dataframe_to_markdown(
            drivers,
            max_rows=100,
        ),
        "",
        source_note(
            [
                "shap_summary",
                "top_forecast_drivers",
            ]
        ),
        "",
    ]

    write_markdown(
        BUSINESS_CONTEXT_DIR
        / "explainability_context.md",
        "\n".join(lines),
    )


# ============================================================================
# 5. MONITORING CONTEXT
# ============================================================================

def build_monitoring_context() -> None:
    """Generate project-derived model-health context."""

    summary = load_json(
        "monitoring_summary"
    )

    performance = load_csv(
        "model_performance"
    )

    drift = load_csv(
        "data_drift"
    )

    lines: list[str] = [
        "# Monitoring Context",
        "",
        "This document contains project-derived model and data "
        "monitoring results.",
        "",
        "These results are monitoring signals, not external "
        "industry assessments.",
        "",
        "## Current monitoring summary",
        "",
        f"- Overall monitoring status: **{summary.get('monitoring_status', 'N/A')}**",
        f"- Drift alerts: **{summary.get('drift_alerts', 'N/A')}**",
        f"- Drift warnings: **{summary.get('drift_warnings', 'N/A')}**",
        f"- Performance alerts: **{summary.get('performance_alerts', 'N/A')}**",
        f"- Performance warnings: **{summary.get('performance_warnings', 'N/A')}**",
        "",
        "## Model performance monitoring",
        "",
        dataframe_to_markdown(
            performance,
            max_rows=100,
        ),
        "",
        "## Data drift monitoring",
        "",
        dataframe_to_markdown(
            drift,
            columns=[
                "series_type",
                "series_id",
                "feature",
                "ks_statistic",
                "ks_p_value",
                "psi",
                "status",
            ],
            max_rows=200,
        ),
        "",
        source_note(
            [
                "monitoring_summary",
                "model_performance",
                "data_drift",
            ]
        ),
        "",
    ]

    write_markdown(
        BUSINESS_CONTEXT_DIR
        / "monitoring_context.md",
        "\n".join(lines),
    )


# ============================================================================
# 6. DATA-QUALITY CONTEXT
# ============================================================================

def build_data_quality_context() -> None:
    """Generate project-derived data-quality context."""

    quality = load_csv(
        "data_quality"
    )

    lines: list[str] = [
        "# Data Quality Context",
        "",
        "This document records data-quality validation information "
        "generated by the project Data Layer.",
        "",
        "## Data-quality checks",
        "",
        dataframe_to_markdown(
            quality,
            max_rows=200,
        ),
        "",
        (
            "The agent should treat these records as the authoritative "
            "project-derived data-quality report rather than inventing "
            "additional data-quality claims."
        ),
        "",
        source_note(
            [
                "data_quality",
            ]
        ),
        "",
    ]

    write_markdown(
        BUSINESS_CONTEXT_DIR
        / "data_quality_context.md",
        "\n".join(lines),
    )


# ============================================================================
# 7. HISTORICAL FORECAST OUTCOMES
# ============================================================================

def build_historical_forecast_outcomes() -> None:
    """
    Create a compact historical forecasting document.

    This records actual vs predicted values from the validated
    walk-forward ensemble output. It does not claim that future
    outcomes are known.
    """

    ensemble = load_csv(
        "overall_ensemble_predictions"
    )

    if ensemble.empty:
        raise ValueError(
            "Overall ensemble prediction report is empty."
        )

    ensemble["timestamp"] = pd.to_datetime(
        ensemble["timestamp"],
        errors="coerce",
    )

    actual = pd.to_numeric(
        ensemble["actual"],
        errors="coerce",
    )

    predicted = pd.to_numeric(
        ensemble["predicted"],
        errors="coerce",
    )

    absolute_error = (
        actual
        - predicted
    ).abs()

    outcome_df = pd.DataFrame(
        {
            "fold":
                ensemble.get(
                    "fold",
                    pd.Series(
                        dtype="float64"
                    ),
                ),
            "timestamp":
                ensemble["timestamp"],
            "actual_revenue":
                actual,
            "forecast_revenue":
                predicted,
            "absolute_error":
                absolute_error,
        }
    )

    lines: list[str] = [
        "# Historical Forecast Outcomes",
        "",
        "This document summarizes realized outcomes from the "
        "project's historical walk-forward ensemble forecasts.",
        "",
        "Each record represents a forecast that was evaluated "
        "against a subsequently observed actual value within the "
        "historical validation period.",
        "",
        "These records should be used for historical comparison, "
        "not as evidence that future actuals are already known.",
        "",
        "## Historical forecast outcomes",
        "",
        dataframe_to_markdown(
            outcome_df.sort_values(
                "timestamp"
            ),
            max_rows=500,
        ),
        "",
        source_note(
            [
                "overall_ensemble_predictions",
            ]
        ),
        "",
    ]

    write_markdown(
        FORECAST_HISTORY_DIR
        / "historical_forecast_outcomes.md",
        "\n".join(lines),
    )


# ============================================================================
# VALIDATION
# ============================================================================

def validate_generated_knowledge_base() -> None:
    """Validate that the expected Stage-1 knowledge documents exist."""

    expected_files = [
        BUSINESS_CONTEXT_DIR
        / "overall_forecast_analysis.md",

        BUSINESS_CONTEXT_DIR
        / "category_forecast_analysis.md",

        BUSINESS_CONTEXT_DIR
        / "regional_forecast_analysis.md",

        BUSINESS_CONTEXT_DIR
        / "explainability_context.md",

        BUSINESS_CONTEXT_DIR
        / "monitoring_context.md",

        BUSINESS_CONTEXT_DIR
        / "data_quality_context.md",

        FORECAST_HISTORY_DIR
        / "historical_forecast_outcomes.md",
    ]

    missing = [
        path
        for path in expected_files
        if not path.is_file()
    ]

    if missing:
        raise RuntimeError(
            "Knowledge-base generation failed. "
            f"Missing files: {missing}"
        )

    empty = [
        path
        for path in expected_files
        if path.stat().st_size == 0
    ]

    if empty:
        raise RuntimeError(
            "Knowledge-base generation produced empty files: "
            f"{empty}"
        )


# ============================================================================
# MAIN
# ============================================================================

def run_knowledge_base_generation() -> None:
    """Generate all Stage-1 project-derived knowledge documents."""

    print(
        "=== KNOWLEDGE BASE STAGE 1 ==="
    )

    ensure_directories()

    print(
        "\nGenerating overall forecast context..."
    )

    build_overall_forecast_analysis()

    print(
        "Generating category forecast context..."
    )

    build_category_forecast_analysis()

    print(
        "Generating regional forecast context..."
    )

    build_regional_forecast_analysis()

    print(
        "Generating explainability context..."
    )

    build_explainability_context()

    print(
        "Generating monitoring context..."
    )

    build_monitoring_context()

    print(
        "Generating data-quality context..."
    )

    build_data_quality_context()

    print(
        "Generating historical forecast outcomes..."
    )

    build_historical_forecast_outcomes()

    validate_generated_knowledge_base()

    generated_files = sorted(
        KNOWLEDGE_BASE_DIR.rglob(
            "*.md"
        )
    )

    print(
        "\n=== KNOWLEDGE BASE GENERATION COMPLETE ==="
    )

    print(
        f"Generated Markdown documents: "
        f"{len(generated_files)}"
    )

    print(
        "\nGenerated files:"
    )

    for path in generated_files:
        print(
            f"- {path.relative_to(PROJECT_ROOT)}"
        )


if __name__ == "__main__":
    run_knowledge_base_generation()